version: '3.8'
services:
  web:
    image: janfalih/santapan-transaction-service
    container_name: santapan-transaction-service-api
    ports:
      - 9091:80
    networks:
      - santapan-network

networks:
  santapan-network:
    driver: bridge
