name: Deploy Go Application

on:
  pull_request:
    branches:
      - deploy-cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: success()  # Only run if previous steps were successful
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker Image
        run: docker build -t janfalih/santapan-api .
      
      - name: Push Docker Image To Docker Hub
        run: docker push janfalih/santapan-api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Create Environment File
        run: |
          cat <<EOF > .env
          DEBUG=True
          SERVER_ADDRESS=:9090
          CONTEXT_TIMEOUT=2
          DATABASE_HOST=localhost
          DATABASE_PORT=5432
          DATABASE_USER=user
          DATABASE_PASSWORD=s4nt4p4nDatab4s3
          DATABASE_NAME=santapan_db
          PORT=9090
          EOF
      - name: Pull Docker Image
        run: docker pull janfalih/santapan-api:latest
      
      - name: Remove Docker Container
        run: docker rm -f santapan-app-container || true
      
      - name: Run Docker Container
        run: docker run -d -p 9090:9090 --name santapan-app-container --env-file .env janfalih/santapan-api
