name: Deploy Go Application

on:
  pull_request:
    branches:
      - deploy-cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create Environment File
        run: |
          echo "DEBUG=True" >> .env
          echo "SERVER_ADDRESS=:9090" >> .env
          echo "CONTEXT_TIMEOUT=2" >> .env
          echo "DATABASE_HOST=localhost" >> .env
          echo "DATABASE_PORT=5432" >> .env
          echo "DATABASE_USER=user" >> .env
          echo "DATABASE_PASSWORD=s4nt4p4nDatab4s3" >> .env
          echo "DATABASE_NAME=santapan_db" >> .env
          echo "PORT=9090" >> .env
      
      - name: Check .env File
        run: cat .env
      
      - name: Upload .env File
        uses: actions/upload-artifact@v2
        with:
          name: env-file
          path: .env

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker Image
        run: docker build -t janfalih/santapan-api .
      
      - name: Push Docker Image To Docker Hub
        run: docker push janfalih/santapan-api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Download .env File
        uses: actions/download-artifact@v2
        with:
          name: env-file
      
      - name: Check .env File on Host
        run: cat .env || echo ".env file not found"
      
      - name: Pull Docker Image
        run: docker pull janfalih/santapan-api:latest
      
      - name: Remove Docker Container
        run: docker rm -f santapan-app-container || true
      
      - name: Run Docker Container
        run: docker run -d -p 9090:9090 --name santapan-app-container --env-file .env janfalih/santapan-api
